#pragma once
#include "util/Joaat.hpp"
#include "CategoryUtils.hpp"

#include <unordered_set>

namespace YimMenu
{
	struct PedScenarioDefinition : public ModelDefinition
	{
	};

	inline std::vector<PedScenarioDefinition> g_PedScenarios =
	{
		{"PROP_HUMAN_PIANO"_J, "Play Piano"},
		{"PROP_HUMAN_PIANO_RIVERBOAT"_J, "Piano Riverboat"},
		{"PROP_HUMAN_PIANO_SKETCHY"_J, "Piano Sketchy"},
		{"PROP_HUMAN_PIANO_UPPERCLASS"_J, "Piano Upperclass"},
		{"WORLD_HUMAN_SIT_GUITAR"_J, "Sit Guitar"},
		{"PROP_HUMAN_SEAT_CHAIR_GUITAR"_J, "Chair Guitar"},
		{"PROP_HUMAN_SEAT_CHAIR_BANJO"_J, "Chair Banjo"},
		{"PROP_HUMAN_SEAT_BENCH_HARMONICA"_J, "Bench Harmonica"},
		{"PROP_HUMAN_SEAT_BENCH_MANDOLIN"_J, "Bench Mandolin"},
		{"PROP_HUMAN_SEAT_BENCH_CONCERTINA"_J, "Bench Concertina"},
		{"PROP_HUMAN_SEAT_BENCH_JAW_HARP"_J, "Bench Jaw Harp"},
		{"WORLD_HUMAN_TRUMPET"_J, "Play Trumpet"},
		{"WORLD_HUMAN_SMOKE"_J, "Smoke"},
		{"PROP_HUMAN_SEAT_CHAIR_SMOKING_TRAIN"_J, "Smoke (Seated)"},
		{"WORLD_CAMP_DUTCH_SMOKE_CIGAR"_J, "Camp Dutch Smoke Cigar"},
		{"WORLD_HUMAN_SMOKE_CIGAR"_J, "Smoke Cigar"},
		{"WORLD_HUMAN_SMOKE_INTERACTION"_J, "Smoke Interaction"},
		{"WORLD_HUMAN_SMOKE_NERVOUS_STRESSED"_J, "Smoke Nervous/Stressed"},
		{"MP_LOBBY_PROP_HUMAN_SEAT_BENCH_PORCH_SMOKING"_J, "Lobby Bench Porch Smoking"},
        	{"WORLD_HUMAN_VOMIT"_J, "Vomit"},
		{"SC_AMB_VIG_VOMIT_WALL"_J, "Vomit (Lean)"},
		{"WORLD_HUMAN_VOMIT_KNEEL"_J, "Vomit (Kneel)"},
		{"WORLD_HUMAN_DRUNK_BRACE_WALL_NO_VOMIT"_J, "Drunk Brace Wall (No Vomit)"},
		{"WORLD_HUMAN_DRUNK_PASSED_OUT_FLOOR"_J, "Drunk Passed Out Floor"},
		{"WORLD_HUMAN_DRINKING"_J, "Drink"},
		{"WORLD_HUMAN_COFFEE_DRINK_WIP"_J, "Coffee Drink WIP"},
		{"WORLD_HUMAN_DRINKING_DRUNK"_J, "Drinking Drunk"},
		{"WORLD_PLAYER_DRINK_WITCHES_BREW"_J, "Drink Witches Brew"},
		{"PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING_TRAIN"_J, "Chair Table Drinking Train"},
		{"MP_LOBBY_PROP_HUMAN_SEAT_BENCH_PORCH_DRINKING"_J, "Lobby Bench Porch Drinking"},
		{"WORLD_PLAYER_SLEEP_GROUND"_J, "Sleep Ground"},
		{"WORLD_HUMAN_SIT_FALL_ASLEEP"_J, "Doze Off"},
		{"WORLD_HUMAN_RE_LOST_DRUNK_SLEEP"_J, "Sleep"},
		{"WORLD_HUMAN_SIT_GROUND"_J, "Sit Down"},
		{"WORLD_HUMAN_SIT_GROUND_READING_BOOK"_J, "Read Book (Seated)"},
		{"PROP_HUMAN_SEAT_CRATE_CLEAN_BOOTS"_J, "Clean Boots (Seated)"},
		{"PROP_HUMAN_SEAT_CHAIR_DRINKING"_J, "Chair Drinking"},
		{"PROP_HUMAN_SEAT_CHAIR_PLAY_KNIFE"_J, "Chair Play Knife"},
		{"PROP_HUMAN_SEAT_CHAIR_READ_NEWSPAPER"_J, "Chair Read Newspaper"},
		{"MP_LOBBY_PROP_HUMAN_SEAT_BENCH_PORCH_DRINKING"_J, "Lobby Bench Porch Drinking"},
		{"MP_LOBBY_PROP_HUMAN_SEAT_BENCH_PORCH_SMOKING"_J, "Lobby Bench Porch Smoking"},
		{"MP_LOBBY_PROP_HUMAN_SEAT_CHAIR"_J, "Lobby Seat Chair"},
		{"MP_LOBBY_PROP_HUMAN_SEAT_CHAIR_KNIFE_BADASS"_J, "Lobby Seat Chair Knife Badass"},
		{"PROP_HUMAN_SEAT_CHAIR_KNIFE_BADASS"_J, "Chair Knife Badass"},
		{"MP_LOBBY_PROP_HUMAN_SEAT_CHAIR_WHITTLE"_J, "Lobby Seat Chair Whittle"},
		{"PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING"_J, "Chair Table Drinking"},
		{"PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING_TRAIN"_J, "Chair Table Drinking Train"},
		{"WORLD_HUMAN_CLIPBOARD"_J, "Clipboard"},
		{"WORLD_HUMAN_BROOM"_J, "Sweep"},
		{"WORLD_HUMAN_CLEAN_TABLE"_J, "Clean Table"},
		{"WORLD_HUMAN_CLEAN_WINDOW"_J, "Clean Window"},
		{"PROP_HUMAN_PUMP_WATER"_J, "Pump Water"},
		{"WORLD_HUMAN_FAN"_J, "Fan"},
		{"WORLD_HUMAN_BADASS"_J, "Badass"},
		{"WORLD_HUMAN_GUARD_MILITARY"_J, "Guard"},
		{"WORLD_HUMAN_GUARD_LEAN_WALL"_J, "Guard (Lean)"},
		{"WORLD_HUMAN_INSPECT"_J, "Inspect"},
		{"WORLD_HUMAN_CROUCH_INSPECT"_J, "Inspect (Crouched)"},
		{"MP_LOBBY_WORLD_HUMAN_CROUCH_INSPECT"_J, "Lobby Crouch Inspect"},
		{"MP_LOBBY_WORLD_HUMAN_CROUCH_INSPECT_MALE_A"_J, "Lobby Crouch Inspect Male A"},
		{"WORLD_HUMAN_KNOCK_DOOR"_J, "Knock Door"},
		{"WORLD_HUMAN_PICKAXE_WALL"_J, "Use Pickaxe"},
		{"WORLD_HUMAN_POCKET_MIRROR"_J, "Use Pocket Mirror"},
		{"WORLD_HUMAN_PITCH_HAY_SCOOP"_J, "Scoop Hay"},
		{"WORLD_HUMAN_SHOPKEEPER"_J, "Shopkeep"},
		{"WORLD_HUMAN_BARTENDER"_J, "Bartend"},
		{"WORLD_HUMAN_SLEDGEHAMMER"_J, "Use Sledgehammer"},
		{"SC_WORLD_HUMAN_PREACHER"_J, "Preach"},
		{"SC_PROP_HUMAN_TORCH"_J, "Hold Torch"},
		{"WORLD_HUMAN_WRITE_NOTEBOOK"_J, "Write Journal"},
		{"WORLD_HUMAN_LEAN_WALL_LEFT"_J, "Lean Left"},
		{"WORLD_HUMAN_LEAN_WALL_RIGHT"_J, "Lean Right"},
		{"WORLD_HUMAN_GRAVE_MOURNING_KNEEL"_J, "Mourn"},
		{"WORLD_HUMAN_WAITING_IMPATIENT"_J, "Waiting Impatient"},
		{"WORLD_HUMAN_GRAVEDIG"_J, "Gravedig"},
		{"WORLD_HUMAN_STARE_STOIC"_J, "Stare Stoic"},
		{"MP_LOBBY_WORLD_HUMAN_STARE_STOIC"_J, "Lobby Stare Stoic"},
		{"MP_LOBBY_WORLD_HUMAN_STERNGUY_IDLES"_J, "Lobby Stern Guy Idles"},
		{"WORLD_HUMAN_FEED_CHICKEN"_J, "Feed Chicken"},
		{"WORLD_HUMAN_FEED_PIGS"_J, "Feed Pigs"},
		{"WORLD_HUMAN_WRITE_NOTEBOOK"_J, "Write Notebook"}
	};

	inline std::unordered_set<std::uint32_t> g_ScenariosUsingChair =
	{
		"PROP_HUMAN_PIANO"_J,
		"PROP_HUMAN_ABIGAIL_PIANO"_J,
		"PROP_HUMAN_PIANO_RIVERBOAT"_J,
		"PROP_HUMAN_PIANO_SKETCHY"_J,
		"PROP_HUMAN_PIANO_UPPERCLASS"_J,
		"PROP_HUMAN_SEAT_CHAIR_GUITAR"_J,
		"PROP_HUMAN_SEAT_CHAIR_BANJO"_J,
		"PROP_HUMAN_SEAT_BENCH_HARMONICA"_J,
		"PROP_HUMAN_SEAT_BENCH_MANDOLIN"_J,
		"PROP_HUMAN_SEAT_BENCH_CONCERTINA"_J,
		"PROP_HUMAN_SEAT_BENCH_JAW_HARP"_J,
		"PROP_HUMAN_SEAT_BENCH_FIDDLE"_J,
                "PROP_HUMAN_SEAT_CHAIR_TABLE_FAN_WHORE"_J,
	        "PROP_HUMAN_SEAT_CRATE_CLEAN_BOOTS"_J,
	        "PROP_HUMAN_SEAT_CHAIR_SAD"_J,
	        "PROP_HUMAN_SEAT_CHAIR_SMOKING_TRAIN"_J,
	        "PROP_HUMAN_SEAT_CHAIR_KNITTING"_J,
	        "PROP_HUMAN_SEAT_CHAIR_SEWING"_J,
		"PROP_HUMAN_SEAT_CHAIR_DRINKING"_J,
		"PROP_HUMAN_SEAT_CHAIR_PLAY_KNIFE"_J,
		"PROP_HUMAN_SEAT_CHAIR_READ_NEWSPAPER"_J,
		"PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING"_J,
		"PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING_BADASS"_J,
		"PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING_BADASS_BEER"_J,
		"PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING_BADASS_WHISKEY"_J,
		"PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING_TRAIN"_J,
		"PROP_HUMAN_SEAT_CHAIR_TABLE_DRINKING_WHISKEY"_J,
		"MP_LOBBY_PROP_HUMAN_SEAT_CHAIR"_J,
		"MP_LOBBY_PROP_HUMAN_SEAT_CHAIR_KNIFE_BADASS"_J,
		"PROP_HUMAN_SEAT_CHAIR_KNIFE_BADASS"_J,
		"MP_LOBBY_PROP_HUMAN_SEAT_CHAIR_WHITTLE"_J
	};

	inline bool DoesScenarioUseChair(std::uint32_t value)
	{
		return g_ScenariosUsingChair.contains(value);
	}
}