#pragma once

#include <array>

namespace YimMenu::Submenus::ManualCloneEmotes
{
	struct Definition
	{
		const char* Name;
		int Category;
	};

	// RDO human kit emotes documented in femga/rdr3_discoveries.
	// Categories: Reaction=0, Action=1, Taunt=2, Greet=3, Dance=5.
	// Gun twirls and animal-only emotes are intentionally excluded here because
	// they require a separate weapon-kit/model setup rather than a normal player emote task.
	inline constexpr std::array kAllHumanPlayerEmotes = {
		Definition{"KIT_EMOTE_ACTION_AIR_BANJO_1", 1},
		Definition{"KIT_EMOTE_ACTION_BECKON_1", 1},
		Definition{"KIT_EMOTE_ACTION_BITING_GOLD_COIN_1", 1},
		Definition{"KIT_EMOTE_ACTION_BLOW_KISS_1", 1},
		Definition{"KIT_EMOTE_ACTION_BOAST_1", 1},
		Definition{"KIT_EMOTE_ACTION_CHECK_POCKET_WATCH_1", 1},
		Definition{"KIT_EMOTE_ACTION_COIN_FLIP_1", 1},
		Definition{"KIT_EMOTE_ACTION_FIST_PUMP_1", 1},
		Definition{"KIT_EMOTE_ACTION_FLEX_1", 1},
		Definition{"KIT_EMOTE_ACTION_FOLLOW_ME_1", 1},
		Definition{"KIT_EMOTE_ACTION_HISSYFIT_1", 1},
		Definition{"KIT_EMOTE_ACTION_HOWL_1", 1},
		Definition{"KIT_EMOTE_ACTION_HYPNOSIS_POCKET_WATCH_1", 1},
		Definition{"KIT_EMOTE_ACTION_IDEA_1", 1},
		Definition{"KIT_EMOTE_ACTION_LETS_CRAFT_1", 1},
		Definition{"KIT_EMOTE_ACTION_LETS_FISH_1", 1},
		Definition{"KIT_EMOTE_ACTION_LETS_GO_1", 1},
		Definition{"KIT_EMOTE_ACTION_LETS_PLAY_CARDS_1", 1},
		Definition{"KIT_EMOTE_ACTION_LISTEN_1", 1},
		Definition{"KIT_EMOTE_ACTION_LOOK_DISTANCE_1", 1},
		Definition{"KIT_EMOTE_ACTION_LOOK_YONDER_1", 1},
		Definition{"KIT_EMOTE_ACTION_NEWTHREADS_1", 1},
		Definition{"KIT_EMOTE_ACTION_POINT_1", 1},
		Definition{"KIT_EMOTE_ACTION_POSSE_UP_1", 1},
		Definition{"KIT_EMOTE_ACTION_PRAYER_1", 1},
		Definition{"KIT_EMOTE_ACTION_PROSPECTOR_JIG_1", 1},
		Definition{"KIT_EMOTE_ACTION_ROCK_PAPER_SCISSORS_1", 1},
		Definition{"KIT_EMOTE_ACTION_SCHEME_1", 1},
		Definition{"KIT_EMOTE_ACTION_SHOOTHIP_1", 1},
		Definition{"KIT_EMOTE_ACTION_SKYWARD_SHOOTING_1", 1},
		Definition{"KIT_EMOTE_ACTION_SMOKE_CIGAR_1", 1},
		Definition{"KIT_EMOTE_ACTION_SMOKE_CIGARETTE_1", 1},
		Definition{"KIT_EMOTE_ACTION_SNOT_ROCKET_1", 1},
		Definition{"KIT_EMOTE_ACTION_SPIN_AND_AIM_1", 1},
		Definition{"KIT_EMOTE_ACTION_SPIT_1", 1},
		Definition{"KIT_EMOTE_ACTION_SPOOKY_1", 1},
		Definition{"KIT_EMOTE_ACTION_STOP_HERE_1", 1},
		Definition{"KIT_EMOTE_ACTION_TAKE_NOTES_1", 1},
		Definition{"KIT_EMOTE_ACTION_WET_YOUR_WHISTLE_1", 1},

		Definition{"KIT_EMOTE_DANCE_AWKWARD_A_1", 5},
		Definition{"KIT_EMOTE_DANCE_CAREFREE_A_1", 5},
		Definition{"KIT_EMOTE_DANCE_CAREFREE_B_1", 5},
		Definition{"KIT_EMOTE_DANCE_CONFIDENT_A_1", 5},
		Definition{"KIT_EMOTE_DANCE_CONFIDENT_B_1", 5},
		Definition{"KIT_EMOTE_DANCE_DRUNK_A_1", 5},
		Definition{"KIT_EMOTE_DANCE_DRUNK_B_1", 5},
		Definition{"KIT_EMOTE_DANCE_FORMAL_A_1", 5},
		Definition{"KIT_EMOTE_DANCE_GRACEFUL_A_1", 5},
		Definition{"KIT_EMOTE_DANCE_OLD_A_1", 5},
		Definition{"KIT_EMOTE_DANCE_WILD_A_1", 5},
		Definition{"KIT_EMOTE_DANCE_WILD_B_1", 5},

		Definition{"KIT_EMOTE_GREET_FANCY_BOW_1", 3},
		Definition{"KIT_EMOTE_GREET_FLYING_KISS_1", 3},
		Definition{"KIT_EMOTE_GREET_GENTLEWAVE_1", 3},
		Definition{"KIT_EMOTE_GREET_GET_OVER_HERE_1", 3},
		Definition{"KIT_EMOTE_GREET_GLAD_1", 3},
		Definition{"KIT_EMOTE_GREET_HAND_SHAKE_1", 3},
		Definition{"KIT_EMOTE_GREET_HAT_FLICK_1", 3},
		Definition{"KIT_EMOTE_GREET_HAT_TIP_1", 3},
		Definition{"KIT_EMOTE_GREET_HEY_YOU_1", 3},
		Definition{"KIT_EMOTE_GREET_OUTPOUR_1", 3},
		Definition{"KIT_EMOTE_GREET_RESPECTFUL_BOW_1", 3},
		Definition{"KIT_EMOTE_GREET_ROUGH_HOUSING_1", 3},
		Definition{"KIT_EMOTE_GREET_SEVEN_1", 3},
		Definition{"KIT_EMOTE_GREET_SUBTLE_WAVE_1", 3},
		Definition{"KIT_EMOTE_GREET_TADA_1", 3},
		Definition{"KIT_EMOTE_GREET_THUMBSUP_1", 3},
		Definition{"KIT_EMOTE_GREET_TOUGH_1", 3},
		Definition{"KIT_EMOTE_GREET_WAVENEAR_1", 3},

		Definition{"KIT_EMOTE_REACTION_AMAZED_1", 0},
		Definition{"KIT_EMOTE_REACTION_APPLAUSE_1", 0},
		Definition{"KIT_EMOTE_REACTION_BEGMERCY_1", 0},
		Definition{"KIT_EMOTE_REACTION_CLAP_ALONG_1", 0},
		Definition{"KIT_EMOTE_REACTION_FACEPALM_1", 0},
		Definition{"KIT_EMOTE_REACTION_HANGOVER_1", 0},
		Definition{"KIT_EMOTE_REACTION_HOW_DARE_YOU_1", 0},
		Definition{"KIT_EMOTE_REACTION_HURL_1", 0},
		Definition{"KIT_EMOTE_REACTION_HUSH_YOUR_MOUTH_1", 0},
		Definition{"KIT_EMOTE_REACTION_JOVIAL_LAUGH_1", 0},
		Definition{"KIT_EMOTE_REACTION_NOD_HEAD_1", 0},
		Definition{"KIT_EMOTE_REACTION_PHEW_1", 0},
		Definition{"KIT_EMOTE_REACTION_POINTLAUGH_1", 0},
		Definition{"KIT_EMOTE_REACTION_SCARED_1", 0},
		Definition{"KIT_EMOTE_REACTION_SHAKEHEAD_1", 0},
		Definition{"KIT_EMOTE_REACTION_SHOT_1", 0},
		Definition{"KIT_EMOTE_REACTION_SHRUG_1", 0},
		Definition{"KIT_EMOTE_REACTION_SHUFFLE_1", 0},
		Definition{"KIT_EMOTE_REACTION_SLOW_CLAP_1", 0},
		Definition{"KIT_EMOTE_REACTION_SNIFFING_1", 0},
		Definition{"KIT_EMOTE_REACTION_SOB_1", 0},
		Definition{"KIT_EMOTE_REACTION_SURRENDER_1", 0},
		Definition{"KIT_EMOTE_REACTION_THANKS_1", 0},
		Definition{"KIT_EMOTE_REACTION_THIS_GUY_1", 0},
		Definition{"KIT_EMOTE_REACTION_THUMBSDOWN_1", 0},
		Definition{"KIT_EMOTE_REACTION_WAG_FINGER_1", 0},
		Definition{"KIT_EMOTE_REACTION_WHO_ME_1", 0},
		Definition{"KIT_EMOTE_REACTION_YEEHAW_1", 0},

		Definition{"KIT_EMOTE_TAUNT_BEST_SHOT_1", 2},
		Definition{"KIT_EMOTE_TAUNT_BOOHOO_1", 2},
		Definition{"KIT_EMOTE_TAUNT_CHICKEN_1", 2},
		Definition{"KIT_EMOTE_TAUNT_COCK_SNOOK_1", 2},
		Definition{"KIT_EMOTE_TAUNT_COUGAR_SNARL_1", 2},
		Definition{"KIT_EMOTE_TAUNT_CRUISING_BRUISING_1", 2},
		Definition{"KIT_EMOTE_TAUNT_CUCKOO_1", 2},
		Definition{"KIT_EMOTE_TAUNT_FIDDLEHEAD_1", 2},
		Definition{"KIT_EMOTE_TAUNT_FINGER_SLINGER_1", 2},
		Definition{"KIT_EMOTE_TAUNT_FLIP_OFF_1", 2},
		Definition{"KIT_EMOTE_TAUNT_FRIGHTEN_1", 2},
		Definition{"KIT_EMOTE_TAUNT_GORILLA_CHEST_1", 2},
		Definition{"KIT_EMOTE_TAUNT_IM_WATCHING_YOU_1", 2},
		Definition{"KIT_EMOTE_TAUNT_INSIGNIFICANT_1", 2},
		Definition{"KIT_EMOTE_TAUNT_PROVOKE_1", 2},
		Definition{"KIT_EMOTE_TAUNT_RIPPER_1", 2},
		Definition{"KIT_EMOTE_TAUNT_THROAT_SLIT_1", 2},
		Definition{"KIT_EMOTE_TAUNT_UP_YOURS_1", 2},
		Definition{"KIT_EMOTE_TAUNT_VERSUS_1", 2},
		Definition{"KIT_EMOTE_TAUNT_WAR_CRY_1", 2},
		Definition{"KIT_EMOTE_TAUNT_YOUSTINK_1", 2},
	};

	inline constexpr std::array kInsultEmotes = {
		Definition{"KIT_EMOTE_TAUNT_FLIP_OFF_1", 2},
		Definition{"KIT_EMOTE_TAUNT_UP_YOURS_1", 2},
		Definition{"KIT_EMOTE_TAUNT_YOUSTINK_1", 2},
		Definition{"KIT_EMOTE_TAUNT_PROVOKE_1", 2},
		Definition{"KIT_EMOTE_TAUNT_THROAT_SLIT_1", 2},
		Definition{"KIT_EMOTE_TAUNT_IM_WATCHING_YOU_1", 2},
		Definition{"KIT_EMOTE_TAUNT_BEST_SHOT_1", 2},
	};

	inline constexpr Definition kMourningEmote{"KIT_EMOTE_REACTION_SOB_1", 0};
}
